config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :locations
  resources :matches
  resources :rendezvous
  resources :pets
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
    belongs_to :user
    has_many :rendezvous
    has_many :activities, through: :rendezvous
    has_many :matches, class_name: "Match", foreign_key: "matchee_id"
    has_many :matches, class_name: "Match", foreign_key: "matched_id"
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:species, :nickname, :likes, :dislikes, :element_type, :img_url, :single, :partner_id)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for @pet do |f| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :species %>
    <%= f.text_field :species %>

    <%= f.label :nickname %>
    <%= f.text_field :nickname %>

    <%= f.label :likes %>
    <%= f.collection_select :likes %>

    <%= f.label :dislikes %>
    <%= f.text_field :dislikes %>

    <%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Species</th>
      <th>Nickname</th>
      <th>Likes</th>
      <th>Dislikes</th>
      <th>Element Type</th>
      <th>Img url</th>
      <th>Single</th>
      <th>Partner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.species %></td>
        <td><%= pet.nickname %></td>
        <td><%= pet.likes %></td>
        <td><%= pet.dislikes %></td>
        <td><%= pet.element_type %></td>
        <td><%= pet.img_url %></td>
        <td><%= pet.single %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Species:</strong>
  <%= @pet.species %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @pet.nickname %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @pet.likes %>
</p>

<p>
  <strong>Dislikes:</strong>
  <%= @pet.dislikes %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pet.element_type %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @pet.img_url %>
</p>

<p>
  <strong>Single:</strong>
  <%= @pet.single %>
</p>

<p>
  <strong>Partner:</strong>
  <%= @pet.partner_id %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>