config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :locations
  resources :matches
  resources :rendezvous
  resources :pets
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rendezvou.rb
class Rendezvou < ApplicationRecord
    belongs_to :pet
    belongs_to :single_pet
    has_many :activities
    has_many :locations, through: :activities
end

app/controllers/rendezvous_controller.rb
class RendezvousController < ApplicationController
  before_action :set_rendezvou, only: [:show, :edit, :update, :destroy]

  # GET /rendezvous
  # GET /rendezvous.json
  def index
    @rendezvous = Rendezvou.all
  end

  # GET /rendezvous/1
  # GET /rendezvous/1.json
  def show
  end

  # GET /rendezvous/new
  def new
    @rendezvou = Rendezvou.new
  end

  # GET /rendezvous/1/edit
  def edit
  end

  # POST /rendezvous
  # POST /rendezvous.json
  def create
    @rendezvou = Rendezvou.new(rendezvou_params)

    respond_to do |format|
      if @rendezvou.save
        format.html { redirect_to @rendezvou, notice: 'Rendezvou was successfully created.' }
        format.json { render :show, status: :created, location: @rendezvou }
      else
        format.html { render :new }
        format.json { render json: @rendezvou.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rendezvous/1
  # PATCH/PUT /rendezvous/1.json
  def update
    respond_to do |format|
      if @rendezvou.update(rendezvou_params)
        format.html { redirect_to @rendezvou, notice: 'Rendezvou was successfully updated.' }
        format.json { render :show, status: :ok, location: @rendezvou }
      else
        format.html { render :edit }
        format.json { render json: @rendezvou.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rendezvous/1
  # DELETE /rendezvous/1.json
  def destroy
    @rendezvou.destroy
    respond_to do |format|
      format.html { redirect_to rendezvous_url, notice: 'Rendezvou was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rendezvou
      @rendezvou = Rendezvou.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rendezvou_params
      params.require(:rendezvou).permit(:activity_id, :location_id, :pet_id, :single_pet_id)
    end
end

app/helpers/rendezvous_helper.rb
module RendezvousHelper
end

app/views/rendezvous/_form.html.erb
<%= form_with(model: rendezvou, local: true) do |form| %>
  <% if rendezvou.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rendezvou.errors.count, "error") %> prohibited this rendezvou from being saved:</h2>

      <ul>
        <% rendezvou.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :activity_id %>
    <%= form.number_field :activity_id %>
  </div>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.number_field :location_id %>
  </div>

  <div class="field">
    <%= form.label :pet_id %>
    <%= form.number_field :pet_id %>
  </div>

  <div class="field">
    <%= form.label :single_pet_id %>
    <%= form.number_field :single_pet_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rendezvous/edit.html.erb
<h1>Editing Rendezvou</h1>

<%= render 'form', rendezvou: @rendezvou %>

<%= link_to 'Show', @rendezvou %> |
<%= link_to 'Back', rendezvous_path %>

app/views/rendezvous/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rendezvous</h1>

<table>
  <thead>
    <tr>
      <th>Activity</th>
      <th>Location</th>
      <th>Pet</th>
      <th>Single pet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rendezvous.each do |rendezvou| %>
      <tr>
        <td><%= rendezvou.activity_id %></td>
        <td><%= rendezvou.location_id %></td>
        <td><%= rendezvou.pet_id %></td>
        <td><%= rendezvou.single_pet_id %></td>
        <td><%= link_to 'Show', rendezvou %></td>
        <td><%= link_to 'Edit', edit_rendezvou_path(rendezvou) %></td>
        <td><%= link_to 'Destroy', rendezvou, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rendezvou', new_rendezvou_path %>

app/views/rendezvous/new.html.erb
<h1>New Rendezvou</h1>

<%= render 'form', rendezvou: @rendezvou %>

<%= link_to 'Back', rendezvous_path %>

app/views/rendezvous/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity:</strong>
  <%= @rendezvou.activity_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @rendezvou.location_id %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @rendezvou.pet_id %>
</p>

<p>
  <strong>Single pet:</strong>
  <%= @rendezvou.single_pet_id %>
</p>

<%= link_to 'Edit', edit_rendezvou_path(@rendezvou) %> |
<%= link_to 'Back', rendezvous_path %>